# mysql数据库配置
#spring:
#datasource:
#username: root
#password: Root_123
#driver-class-name: com.mysql.cj.jdbc.Driver
#url: jdbc:mysql://localhost:3306/homework?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
## mybatis配置文件位置
#mybatis:
#mapper-locations: classpath:com/ql/mapper/*.xml
#type-aliases-package: com.ql.domain
#configuration:
##log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
## 日志显示sql信息
#logging:
#level:
#com.zz.springbootmybatis.mapper: debug
## pagehelper
#pagehelper:
#helperDialect: mysql
#reasonable: true
#supportMethodsArguments: true
#params: count=countSql